### ISSUE TITLE
Bulid failed

### ISSUE THREAD

**Issue by uselessbug** [alcexhim/UniversalEditor#3]
Could not find the project file /MBS.Audio/MBS.Audio/MBS.Audio.csproj

**Comment by KokoseiJ** [comment]
Can confirm, library doesn't seem to be obtainable.

Can you release the MBS.Audio library? or tell us the latest commit that didn't utilize it?

**Comment by uselessbug** [comment]
Still failed though with MBS.Audio, might have something conflict in this repo...
